Repository pi-prakhar/r2d2, pull requests merged in 2025-04, with the labels that each got.

#1 Feature: autocompletion for r2d2
  README.md
  cmd/completion.go
  cmd/root.go
  cmd/update-tag.go
  cmd/watch-images.go
  cmd/watch-tags.go
Labels: enhancement

#2 Feature: added get pod log
  utils/watch_logs.go
Labels: enhancement

#3 Feature: status in watch tags and code refactoring
  cmd/root.go
  cmd/update-tag.go
  cmd/update_tag.go
  cmd/watch_images.go
  cmd/watch_tags.go
  constants/descriptions.go
  constants/frequency.go
  constants/status.go
  k8s/deployment_info.go
  k8s/update_tag.go
  utils/status_color.go
  utils/table/table.go
  utils/table/watch_images.go
  utils/table/watch_tags.go
Labels: enhancement

#5 Feature: added restart pod and deployment command
  cmd/restart.go
  cmd/restart_deployment.go
  cmd/restart_pod.go
  k8s/restart.go
Labels: enhancement

#7 Docs: modified the README.md to latest
  utils/update_check.go
Labels: documentation

#8 Bug: fixed version swap issue
  utils/update_check.go
Labels: bug

#9 Docs: add contributing.md
  CONTRIBUTING.md
  README.md
Labels: documentation

#10 fix: completion logs removed in production
  cmd/completion.go
Labels: bug

#11 Docs: create LICENSE
  LICENSE
Labels: documentation
